name: 'parallel-plugin-actions'

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute jacocoTestReport
        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
      - name: Build with Gradle
        run: ./gradlew build -x test -x functionalTest --refresh-dependencies --no-daemon --continue
      - name: Run functional tests
        run: ./gradlew functionalTest
      - name: Push codeCoverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute jacocoTestReport
        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
      - name: Build with Gradle
        run: ./gradlew build -x test -x functionalTest --refresh-dependencies --no-daemon --continue
      - name: Run functional tests
        run: ./gradlew functionalTest
      - name: Push codeCoverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Publish plugin
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.KEY_GRADLE }} -Pgradle.publish.secret=${{ secrets.SECRET_GRADLE }}
